### PR TITLE
:cake: Major - Work In Progress

### PR DESCRIPTION
**Pull request by iwatakeshi**
Any new changes will happen here for #111, #109 #108 #110 instead of branch 4.0.0 so please do not merge.

I've thought about using TypeScript for v4, but for familiarity's sake, I decided to stick with JavaScript's ES6 (without a transpiler for simplicity). Note that the next version will require Node v5 or above.
Anyways, here are the current changes:

* Removed almost everything.
* Added a new CLI.
* Replaced JSHint with ESLint.
* Added editor config.

### CODE REVIEW

**Comment by iwatakeshi** [comment]
The CLI seems like it's getting set in place and should be usable. If anyone has the time to try it out and provide some feedback, I would greatly appreciate it. :smile:

**Comment by iwatakeshi** [comment]
#### Update:

##### Here's what's new so far:

* The sources are so small it's easier to contribute.
* Added Parser and Compiler class.
* Mr. Doc can parse Javascript (ES6, Flow, whatever Babel, Espree, or Acorn can handle) and output to JSON.
* Switched from "walking directories" with `walk` to `vinyl-fs` for glob support.
* Mr. Doc Class is now front-end agnostic. Meaning, it doesn't care whether a CLI, gulp, or grunt is used.

... and more.
##### Here's what's left:

* HTML
  * Templates
  * Themes
* Markdown (maybe)
* Tests

I really would love to have some help in getting ideas on how themes should work so if anyone would like to contribute, please feel free to do so.

ping @gr2m, @FGRibreau

**Comment by FGRibreau** [comment]
@iwatakeshi good for me, awesome work! :+1:

**Comment by gr2m** [comment]
Thanks for all the hard work < 3 I’m traveling right and won’t have time to look into it in the next 2 weeks, but just wanted to say that I really appreciate your hard work!

**Comment by iwatakeshi** [comment]
#### Update:

### Completed:

* Moved majority of utilities into `mr-doc-utils` with an exception of `log.js`.
* Moved the parser factory into its own repo under the name of `parser`.

### TODO:

* Move the compiler factory into its own repo under the name of `compiler`

**Comment by iwatakeshi** [comment]
#### Update:

##### Completed:

* Moved the compiler factory into its own repo under the name of `compiler`

##### TODO:

* Research #116 
* Merge #113 
* Themes / HTML

**Comment by iwatakeshi** [comment]
#### Update:

The new CLI is ready to be merged.
I will continue to work on the compiler for Themes/HTML. For tracking see #110.

**Comment by gr2m** [comment]
👏

**Pull request merged**
