### PR TITLE
Add a way to include themes using a relative path.

### PR DESCRIPTION
**Pull request by drewloomer**
I've run into a situation where I cannot (for legal reasons) publish my theme to npm. There should be a way to reference themes from the file system. This is a solution, albeit not very elegant. 

Also, adjusted tabs in config.json.

### CODE REVIEW

**Comment by drewloomer** [comment]
Not sure why the CI build failed :frowning:

**Comment by iwatakeshi** [comment]
Completely understandable. :smile: At the moment I wont be able to do much (as far as looking into it and work on it). However, I can probably give you some ideas that I just thought when you mentioned about private themes:

The current solution may work but it's a little hacky. I would look into the Options class and a new boolean option : 
` -p, --private <private> Marks the theme as private located relative to the project. `

Then when that option is passed to the Theme class, it would know how to deal with themes that are not NPM based themes in [`findTheme()`](https://github.com/mr-doc/mr-doc/blob/master/lib/theme.js#L146-L180).

Let me know if all seems to pass or if you're stuck on something that I may help. I'll then merge and publish this once it's done. :smile:

**Comment by iwatakeshi** [comment]
@drewloomer for the build issue, just add `/*jshint loopfunc: true */` to the top of `mr-doc.js` and that will suppress it in the mean time :smile:

**Comment by drewloomer** [comment]
@iwatakeshi I've added the `-p` flag as you suggested and things seem to be working right. I've added a test for that too. Let me know if you see any issues. Thanks!

**Comment by iwatakeshi** [comment]
:+1: Looks good! Thanks!

**Comment by drewloomer** [comment]
Thanks! When do you think we will see a version bump and push to npm?

**Comment by iwatakeshi** [comment]
Pretty soon. I'll have it published within an hour or two. :smiley:

**Comment by drewloomer** [comment]
Wow! That would be awesome. Thanks a bunch.

**Comment by iwatakeshi** [comment]
:+1: Published! Thanks for the contributions!

**Pull request merged**
