### PR TITLE
3.0.0

### PR DESCRIPTION
**Pull request by iwatakeshi**
This update contains bug fixes from the recent backend switch.

#### Fixes
* Fixed a critical issue where templates were no longer recognized. Themes heavily depend on the `template` option for test purposes.
* Fixed the relative path issue by adding a `path` to the targets and is accessible in the template file with the `target.path` shorthand.
* Fixed the `name` option (formerly `title`) to work

#### Additions
* Added a new `kit` option which tells Mr. Doc that a theme kit is used and copying the assets is required.
* Added a new `config.json` file that contains both the `.jshintrc` and `beautify` options.

#### Other
* Cleaned up code.
* Cleaned up readme
* Changed `.jshintrc` max length from 80 to 120.
* **[Breaking]** Changed the options so that it can be easier to use. See https://github.com/mr-doc/mr-doc/blob/3.0.0/bin/mr-doc#L35-L43
* Cleaned bin.

@FGRibreau  @cliftonc  I'll need some help in testing. So far my local cayman-theme works perfectly on my end. :)

### CODE REVIEW

**Comment by iwatakeshi** [comment]
@FGRibreau This is still a work in progress, but I'm currently stuck and would like some help. Everything but the relative paths in the Jade template works. I'm not sure what exactly is the issue because if you run `gulp build` in `mr-doc-theme-cayman` the nested directories work perfectly but running from the CLI on a project doesn't work too well.
screen shot 2015-09-21 at 4 00 30 pm

The red box shows the differences in the path (the red box on the right is incorrect). The blue box shows that it has the correct relative path.

Any help would greatly be appreciated :)

**Comment by cliftonc** [comment]
It's almost certainly something to do with differences between ```__dirname``` and ```process.cwd()``` when using a global install (e.g. mr-doc is installed in your npm folder vs in the folder your in).  Let me take a look at that part of the code.

**Comment by iwatakeshi** [comment]
@cliftonc thanks!

**Comment by iwatakeshi** [comment]
@FGRibreau @cliftonc Good news! :) I finally fixed the relative path issue. It was one of those "hit my forehead" moments... Anyways, the issue was partially in how I set the path in the themes but now with the new `target.path` (or `path`) shorthand, templates can easily add the path to the target. You can see the addition here: https://github.com/mr-doc/mr-doc/blob/3.0.0/lib/mr-doc.js#L148

I think this is ready for release. @FGRibreau if you wouldn't mind, would you check if everything look good then generate the docs for gh-pages? Issue #88 will hopefully be solved in the next update...probably in 3.0.1 or so. :)

**Comment by cliftonc** [comment]
You need to update the docs command for mr-doc:

```
/* 
 * Runs the mr-doc command and builds the docs 
* Install other themes here, generate docs for each.
*/
gulp.task('doc', ['build'], shell.task([  
  './bin/mr-doc --source lib --output docs/themes/mr-doc-theme-default --name mr-doc'  
]));
```

Otherwise it works fine for me.

**Comment by iwatakeshi** [comment]
I ran the command but getting an error?

```bash
Takeshis-MacBook-Pro:mr-doc iwatakeshi$ gulp docs
[00:21:03] Using gulpfile ~/Documents/GitHub/mr-doc/gulpfile.js
[00:21:03] Starting 'backup'...
[00:21:03] Finished 'backup' after 26 ms
[00:21:03] Starting 'beautify'...
[00:21:03] Finished 'beautify' after 63 ms
[00:21:03] Starting 'lib'...
[00:21:04] Finished 'lib' after 1.13 s
[00:21:04] Starting 'mocha'...


  Symbol
    map
      ✓ should map correctly
    compact
      ✓ should compact correctly


  2 passing (11ms)

[00:21:05] Finished 'mocha' after 70 ms
[00:21:05] Starting 'build'...
[00:21:05] Finished 'build' after 30 μs
[00:21:05] Starting 'doc'...
Mr. Doc [info]: Using theme [mr-doc-theme-default]
Mr. Doc [info]: ⠏ Rendering template.
[00:21:06] Finished 'doc' after 1.92 s
[00:21:06] Starting 'gh-pages'...
[00:21:07] 'gh-pages' errored after 55 ms
[00:21:07] Error in plugin 'gulp-gh-pages'
Message:
    Command failed: /bin/sh -c git rev-list --pretty=raw --max-count=1 
usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
  limiting output:
    --max-count=<n>
    --max-age=<epoch>
    --min-age=<epoch>
    --sparse
    --no-merges
    --min-parents=<n>
    --no-min-parents
    --max-parents=<n>
    --no-max-parents
    --remove-empty
    --all
    --branches
    --tags
    --remotes
    --stdin
    --quiet
  ordering output:
    --topo-order
    --date-order
    --reverse
  formatting output:
    --parents
    --children
    --objects | --objects-edge
    --unpacked
    --header | --pretty
    --abbrev=<n> | --no-abbrev
    --abbrev-commit
    --left-right
  special purpose:
    --bisect
    --bisect-vars
    --bisect-all

Details:
    killed: false
    code: 129
    signal: null
    cmd: /bin/sh -c git rev-list --pretty=raw --max-count=1 
Takeshis-MacBook-Pro:mr-doc iwatakeshi$ 

```

**Comment by cliftonc** [comment]
I think it's because you're on a branch, and this repo doesn't appear to have master - linked to the problem on the other ticket I suspect.

**Comment by iwatakeshi** [comment]
@FGRibreau @cliftonc I'll go ahead and merge this and see what happens on master.

**Comment by cliftonc** [comment]
It's because of this:

https://github.com/shinnn/gulp-gh-pages/issues/42

We need to create the gh-pages branch (local and remote) for the gulp plugin to work.

**Pull request merged**
